// ════════════════════════════════════════════════════════
//  profile-inject.js  v2
//  Reads profile from localStorage.
//  Injects a personalised "What this means for [Name]"
//  panel on every science page.
//  Panel content is generated by Claude — not find/replace.
//  Each page declares its type via:
//    <meta name="bl-inject" content="TYPE">
// ════════════════════════════════════════════════════════

(function () {
  const page = location.pathname.split('/').pop();
  if (!page || page === 'bodylens-onboard.html' || page === 'bodylens-reset.html') return;

  let profile;
  try {
    const raw = localStorage.getItem('bl_profile');
    if (!raw) return;
    profile = JSON.parse(raw);
    if (!profile || !profile.name) return;
  } catch (e) { return; }

  window.__BL_PROFILE__ = profile;

  const meta = document.querySelector('meta[name="bl-inject"]');
  if (!meta) return;
  const pageType = meta.getAttribute('content');

  // Cache key — regenerate daily or if profile changes
  const cacheKey = 'bl_inject_' + pageType + '_' + new Date().toISOString().slice(0, 10);
  const cached   = tryGet(cacheKey);

  document.addEventListener('DOMContentLoaded', () => {
    if (cached) {
      injectPanel(cached, profile);
    } else {
      injectPanel(buildStaticPanel(pageType, profile), profile);
      generateAIPanel(pageType, profile).then(aiContent => {
        if (aiContent) {
          trySet(cacheKey, aiContent);
          const existing = document.getElementById('bl-inject-panel');
          if (existing) existing.remove();
          injectPanel(aiContent, profile);
        }
      });
    }
  });

  // ── INJECT ──────────────────────────────────────────────
  function injectPanel(content, p) {
    const panel = document.createElement('div');
    panel.id = 'bl-inject-panel';
    panel.style.cssText = [
      'background:#131918',
      'border-top:1px solid rgba(0,200,160,0.2)',
      'border-bottom:1px solid rgba(255,255,255,0.05)',
      'padding:20px 0',
      'position:relative',
      'z-index:10',
    ].join(';');

    panel.innerHTML = `
      <div style="max-width:1080px;margin:0 auto;padding:0 32px;">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:24px;flex-wrap:wrap;">
          <div style="flex:1;min-width:240px;">
            <div style="font-size:9px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;
              color:#00c8a0;margin-bottom:12px;display:flex;align-items:center;gap:8px;">
              <span style="width:14px;height:1px;background:#00c8a0;display:inline-block;flex-shrink:0;"></span>
              What this means for ${p.name}
            </div>
            <div id="bl-inject-rows" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:0 28px;">
              ${content.rows || '<div style="color:#8a9490;font-size:12px;">Loading…</div>'}
            </div>
            ${content.callout ? `
              <div style="margin-top:12px;padding:11px 16px;
                background:rgba(0,200,160,0.05);
                border-left:2px solid rgba(0,200,160,0.3);
                border-radius:0 4px 4px 0;
                font-size:12px;font-weight:300;color:#8a9490;line-height:1.75;">
                ${content.callout}
              </div>` : ''}
          </div>
          <a href="bodylens-day.html"
            style="flex-shrink:0;padding:9px 18px;background:#00c8a0;border-radius:4px;
            font-size:10px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;
            color:#0c1010;text-decoration:none;white-space:nowrap;align-self:flex-start;">
            Today's plan →
          </a>
        </div>
      </div>`;

    // Insert after first section/hero
    const nav   = document.querySelector('.site-nav');
    const first = document.querySelector('.dk, .lt, section, .hero, .page, main, .content');
    if (first && first !== nav) {
      first.insertAdjacentElement('beforebegin', panel);
    } else if (nav) {
      nav.insertAdjacentElement('afterend', panel);
    } else {
      document.body.insertAdjacentElement('afterbegin', panel);
    }
  }

  // ── ROW BUILDER ─────────────────────────────────────────
  function row(label, value, color) {
    return `<div style="display:flex;justify-content:space-between;align-items:baseline;
      padding:7px 0;border-bottom:1px solid rgba(0,200,160,0.08);font-size:12px;gap:12px;">
      <span style="font-weight:400;color:#8a9490;flex-shrink:0;">${label}</span>
      <span style="font-weight:500;color:${color || '#e8e3da'};text-align:right;line-height:1.4;">${value}</span>
    </div>`;
  }

  // ── STATIC PANEL (shown immediately before AI responds) ──
  function buildStaticPanel(type, p) {
    const DAY_MAP  = {0:6,1:0,2:1,3:2,4:3,5:4,6:5};
    const DAY_NAMES = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
    const todayIdx  = DAY_MAP[new Date().getDay()];
    const weekPlan  = p.weekPlan || [];
    const todayPlan = weekPlan[todayIdx] || {};
    const injuries  = p.injuryAssessments || p.injuries || [];
    const isFemale  = (p.sex || '').toLowerCase() === 'female';

    switch (type) {
      case 'longevity':
        return { rows:
          row('Name', p.name) +
          row('Age', p.age + (isFemale && p.age >= 35 ? ' — late 30s hormonal window' : ''), '#00c8a0') +
          row('Sex', p.sex || '—', isFemale ? '#c8941e' : '') +
          row('Goal', p.goal || '—') +
          row('Sleep', p.sleep || '—', (p.sleep||'').includes('8') ? '#00c8a0' : '#c47c18') +
          row('Recovery', (p.recoveryTools||[]).join(', ') || 'None')
        };

      case 'alcohol':
        return { rows:
          row('Your habit', p.alcoholHabit || '—') +
          row('Today', todayPlan.priority === 'training' ? 'Training day — alcohol off' : 'Rest day', todayPlan.priority === 'training' ? '#d94e35' : '#00c8a0') +
          row('Rule', 'No alcohol on training days', '#d94e35') +
          row(isFemale ? 'Female note' : 'Note', isFemale ? 'Women reach higher BAC at same dose — metabolism ~20% slower' : 'Alcohol blocks mTOR directly', '#c8941e')
        };

      case 'training':
        return { rows:
          row('Your split', `${p.trainingDays||4} days/week`) +
          row('Today', `${DAY_NAMES[todayIdx]} — ${todayPlan.type||'Rest'}`, todayPlan.priority==='training'?'#00c8a0':'#8a9490') +
          row('Experience', p.experience || '—') +
          row('Injuries', injuries.length ? injuries.map(i=>i.location||i).join(', ') : 'None', injuries.length ? '#c8941e' : '#00c8a0')
        };

      case 'fuel':
        return { rows:
          row('Calories', `${p.calories||'—'} kcal`, '#00c8a0') +
          row('Protein', `${p.protein||'—'}g`, '#00c8a0') +
          row('Eating window', p.fastingWindow||p.eatingWindow||'Flexible') +
          row('Avoid', (p.foodExclusions||[]).join(', ')||'None', (p.foodExclusions||[]).length?'#d94e35':'#8a9490')
        };

      case 'hunger':
        return { rows:
          row('Energy pattern', p.energyPattern || '—') +
          row('Trigger foods', p.triggerFoods||'None', p.triggerFoods&&!p.triggerFoods.includes('None')?'#d94e35':'#8a9490') +
          row('Eating window', p.fastingWindow||p.eatingWindow||'Flexible')
        };

      default:
        return { rows: row('Profile', p.name + ' · ' + (p.goal||'—')) };
    }
  }

  // ── AI PANEL GENERATOR ───────────────────────────────────
  async function generateAIPanel(type, p) {
    const isFemale  = (p.sex || '').toLowerCase() === 'female';
    const injuries  = p.injuryAssessments || p.injuries || [];
    const supps     = p.supplements || [];
    const weekPlan  = p.weekPlan || [];
    const DAY_MAP   = {0:6,1:0,2:1,3:2,4:3,5:4,6:5};
    const todayIdx  = DAY_MAP[new Date().getDay()];
    const todayPlan = weekPlan[todayIdx] || {};
    const trainingDayNames = weekPlan.filter(d=>d.priority==='training').map(d=>d.day).join(', ');

    const pageDescriptions = {
      longevity:   'The Longevity Map page — covers decades of biological change, VO₂max, muscle preservation, hormonal shifts, bone density',
      alcohol:     'The Alcohol page — covers how alcohol affects sleep, hormones, mTOR, fat oxidation, and recovery',
      training:    'The Training Science page — covers rep ranges, progressive overload, muscle protein synthesis, recovery, splits',
      fuel:        'The Food System page — covers macros, meal timing, leucine threshold, protein quality, carb timing',
      hunger:      'The Hunger Science page — covers ghrelin, leptin, satiety, glycaemic response, intermittent fasting',
      optimal:     'The Machine page — covers the full daily system: wake routine, supplements, sleep, cortisol, HGH, recovery',
      weightloss:  'The Weight Loss Science page — covers energy deficit, fat oxidation, EPOC, body recomposition',
      body:        'The Body Explorer page — interactive muscle guide covering muscle anatomy and training applications',
      synthesis:   'The How It Runs page — covers the Signal/Build/Protect/Repeat framework for the full programme',
      story:       'The Story page — narrative covering one full day from wake to sleep, all systems connected',
      science:     'The Science page — filterable science cards covering all topics',
    };

    const prompt = `You are writing a short personalised science commentary panel for the BodyLens app.

PAGE: ${pageDescriptions[type] || type}

USER PROFILE:
Name: ${p.name}
Age: ${p.age} | Sex: ${p.sex} | Height: ${p.height}cm | Weight: ${p.weight}kg
Body fat: ${p.bodyFat||'unknown'}% | Fat storage: ${p.fatStorage||'—'}
Goal: ${p.goal} | Target: ${p.target||'—'}
Experience: ${p.experience||'—'} | Training days: ${p.trainingDays||4}/week (${trainingDayNames})
Wake time: ${p.wakeTime||'07:00'} | Eating window: ${p.fastingWindow||p.eatingWindow||'flexible'}
Diet: ${p.dietType||'—'} | Trigger foods: ${p.triggerFoods||'none'}
Energy pattern: ${p.energyPattern||'—'}
Sleep: ${p.sleep||'—'} | Alcohol: ${p.alcoholHabit||'—'}
Recovery tools: ${(p.recoveryTools||[]).join(', ')||'none'}
Injuries: ${injuries.length ? injuries.map(i=>(i.location||i)+(i.assessment?' — '+i.assessment:'')).join('; ') : 'none'}
Non-negotiables: ${(p.nonNegotiables||[]).join(', ')||'none'}
Supplements: ${supps.map(s=>s.name+' '+s.dose).join(', ')||'none'}
Today: ${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][todayIdx]} — ${todayPlan.type||'Rest'} (${todayPlan.priority==='training'?'training day':'rest day'})
Calories: ${p.calories||'—'} | Protein: ${p.protein||'—'}g | Carbs: ${p.carbs||'—'}g | Fat: ${p.fat||'—'}g

IMPORTANT: ${isFemale ? `This is a ${p.age}-year-old WOMAN. The science commentary must account for female physiology — oestrogen, progesterone, hormonal cycle effects on training and recovery, female fat distribution patterns (${p.fatStorage||'—'}), bone density considerations, and how ${p.age >= 35 ? 'perimenopause proximity affects the relevant science on this page' : 'female hormonal patterns affect the relevant science on this page'}.` : `This is a ${p.age}-year-old man. The science commentary must account for male physiology — testosterone dynamics, male fat distribution, and how his specific age affects the relevant science on this page.`}

Write a panel with:
1. 4-6 data rows showing what the page's science means specifically for this person
2. A 2-3 sentence callout that explains the single most important insight from this page for their specific situation — accounting for their sex, age, goal, and relevant data

The rows and callout must:
- Be specific to their profile, not generic
- Account for their SEX throughout — different physiology = different application of the science
- Reference their actual numbers (calories, protein, training days, injuries if relevant)
- Explain WHY the science applies differently to them given who they are

Return ONLY a JSON object:
{
  "rows": "HTML string of row divs",
  "callout": "2-3 sentence text"
}

Each row div format:
<div style="display:flex;justify-content:space-between;align-items:baseline;padding:7px 0;border-bottom:1px solid rgba(0,200,160,0.08);font-size:12px;gap:12px;"><span style="font-weight:400;color:#8a9490;flex-shrink:0;">LABEL</span><span style="font-weight:500;color:COLOR;text-align:right;line-height:1.4;">VALUE</span></div>

Colors: #00c8a0 (positive/jade), #c8941e (caution/amber), #d94e35 (warning/red), #e8e3da (neutral)`;

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 800,
          system: 'You write personalised science commentary. Return only valid JSON with "rows" and "callout" keys. No markdown.',
          messages: [{ role: 'user', content: prompt }],
        }),
      });
      const data = await res.json();
      const text = data.content?.map(b => b.text || '').join('') || '';
      const match = text.match(/\{[\s\S]*\}/);
      if (!match) return null;
      return JSON.parse(match[0]);
    } catch (e) {
      console.error('Inject AI error:', e);
      return null;
    }
  }

  // ── STORAGE HELPERS ──────────────────────────────────────
  function tryGet(key) {
    try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : null; } catch(e) { return null; }
  }
  function trySet(key, val) {
    try { localStorage.setItem(key, JSON.stringify(val)); } catch(e) {}
  }

})();
